### PR TITLE
Request to merge dev into main

### PR DESCRIPTION
**Pull request by flemton**
Dear reviewer, it is a pleasure to request a review for my PR before merging into main from dev.
Below were the PRs with commits made to meet the project requirements:

- [Merge pull request](https://github.com/flemton/budget_app/commit/b19cb3df8fcff0b9ac4786b68793661083aa897f) https://github.com/flemton/budget_app/pull/1 [from flemton/feature/setup](https://github.com/flemton/budget_app/commit/b19cb3df8fcff0b9ac4786b68793661083aa897f)
- [Merge pull request](https://github.com/flemton/budget_app/commit/4467913ac721a91929b37ea8e4fcba89fb0db1a9) https://github.com/flemton/budget_app/pull/2 [from flemton/feature/models_and_auth](https://github.com/flemton/budget_app/commit/4467913ac721a91929b37ea8e4fcba89fb0db1a9)
- [Merge pull request](https://github.com/flemton/budget_app/commit/89a875772d50b2a119d1cb893d30aa2cc33fa890) https://github.com/flemton/budget_app/pull/3 [from flemton/feature/tests](https://github.com/flemton/budget_app/commit/89a875772d50b2a119d1cb893d30aa2cc33fa890)
- [Merge pull request](https://github.com/flemton/budget_app/commit/5d9534ba1d28358b7e7a9b2428937f7fa8a6ef5c) https://github.com/flemton/budget_app/pull/4 [from flemton/feature/controllers_and_routes](https://github.com/flemton/budget_app/commit/5d9534ba1d28358b7e7a9b2428937f7fa8a6ef5c)
- [Merge pull request](https://github.com/flemton/budget_app/commit/21432e3d88785caa0a3ed014643200f2aaab125c) https://github.com/flemton/budget_app/pull/5 [from flemton/feature/linters_setup](https://github.com/flemton/budget_app/commit/21432e3d88785caa0a3ed014643200f2aaab125c)
- [Merge pull request](https://github.com/flemton/budget_app/commit/29b455c0d8f316f492d1a0ffb3dcb1501d047d45) https://github.com/flemton/budget_app/pull/6 [from flemton/feature/styling](https://github.com/flemton/budget_app/commit/29b455c0d8f316f492d1a0ffb3dcb1501d047d45)
- [Merge pull request](https://github.com/flemton/budget_app/commit/e62fcdfa50c3bdb807d47696b3f4394ee16990b7) https://github.com/flemton/budget_app/pull/7 [from flemton/feature/tests](https://github.com/flemton/budget_app/commit/e62fcdfa50c3bdb807d47696b3f4394ee16990b7)
- [Merge pull request](https://github.com/flemton/budget_app/commit/4dc40382718f01a4d520197ae58ce814676e7439) https://github.com/flemton/budget_app/pull/8 [from flemton/feature/readme](https://github.com/flemton/budget_app/commit/4dc40382718f01a4d520197ae58ce814676e7439)

### CODE REVIEW

**Review by OLIPLICHE — COMMENTED** [review]
Hi @flemton, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow **Gitflow** as requested the project requirement

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by flemton** [comment]
Hello sir @OLIPLICHE, I do not understand what you meant when you said my project does not follow GitFlow, could you please throw more light on that?

**Comment by OLIPLICHE** [comment]
- Read Here 👉 [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)
- Here is the general requirements:


Capture

**Comment by flemton** [comment]
Thank you very much Mr @OLIPLICHE  for sharing the link, but from the requirement below it says we should submit a review after the complete project and not after each feature (milestone). if you check my Pull requests in the repo you can see I implemented each feature in a feature branch, but because we are submitting as a complete project that's why I merged all features and created a PR from that as a complete project and submitted, thanks.

Screenshot 2023-11-26 at 1 56 00 AM

**Comment by KayLemba** [comment]
Hi @flemton,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
Invalid Code Review Request

You have submitted a project, that does not follow Gitflow as requested the project requirement

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

As requested by the previous code reviewer kindly compare feature branch to development for this is not a group capstone.

**Pull request closed without merging**
